#!/bin/bash

function command_install {

    function help {

        echo -e "Install mysql"

    }

    function process {

        set -e

        if is_command_exist mysql
        then
            exit 0
        else
            verbose 1 "Visit http://www.mysql.com/downloads/ to install mysql"
            exit 1
        fi
        
    }
}

function command_start {

    function help {

        echo -e "Start mysql"

    }
    
    function cmd {
        /usr/local/mysql/support-files/mysql.server start
    }

    function process {

        verbose 1 "Starting mysql..."
        exesudo cmd
        
    }
}

function command_stop {

    function help {

        echo -e "Stop mysql"

    }
    
    function cmd {
        /usr/local/mysql/support-files/mysql.server stop
    }

    function process {

        verbose 1 "Stopping mysql..."
        exesudo cmd

    }
}

function command_restart {

    function help {

        echo -e "Restart mysql"

    }
    
    function cmd {
        /usr/local/mysql/support-files/mysql.server restart
    }

    function process {

        verbose 1 "Restarting mysql..."
        exesudo cmd
    }
}

function command_doctor {

    function help {

        echo -e "Check mysql install sanity"

    }

    function process {

        pulsion start

        sleep 3

        set -e
        verbose 1 "Test of mysql"
        echo quit | mysql -uroot
        verbose 1 "Connection Ok"
    }
}
