#!/bin/bash

function command_install {

    function help {

        echo -e "Install mysql"

    }

    function process {

        set -e

        brew update
        brew upgrade
        brew install mysql
        mysql_secure_installation
    }
}

function command_start {

    function help {

        echo -e "Start mysql"

    }

    function process {

        verbose 1 "Starting mysql..."
        launchctl load /usr/local/opt/mysql/homebrew.mxcl.mysql.plist

    }
}

function command_stop {

    function help {

        echo -e "Stop mysql"

    }

    function process {

        verbose 1 "Stopping mysql..."
        launchctl unload /usr/local/opt/mysql/homebrew.mxcl.mysql.plist

    }
}

function command_restart {

    function help {

        echo -e "Restart mysql"

    }

    function process {

        pulsion stop
        pulsion start

    }
}

function command_doctor {

    function help {

        echo -e "Check mysql install sanity"

    }

    function process {

        verbose 1 "Starting mysql..."
        launchctl load /usr/local/opt/mysql/homebrew.mxcl.mysql.plist

        sleep 2

        set -e
        verbose 1 "Test of mysql"
        echo quit | mysql -uroot
        verbose 1 "Connection Ok"
    }
}